services:
  postgres:
    image: postgres:15
    container_name: brisq-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: brisq_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d brisq_auth"]
      interval: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: brisq-auth
    env_file:
      - path: ./auth/.env.development
        required: true
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/brisq_auth
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./auth/src
          target: /app/auth/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./auth/package.json
        - action: rebuild
          path: ./common/src
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: brisq-api-gateway
    ports:
      - "3000:3000"
    env_file:
      - path: ./api-gateway/.env.development
        required: true
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./api-gateway/src
          target: /app/api-gateway/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./api-gateway/package.json
        - action: rebuild
          path: ./common/src        

volumes:
  postgres_data:
    name: brisq_postgres_data