services:
  postgres-auth:
    image: postgres:15
    container_name: brisq-postgres-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}"]
      interval: 5s
      retries: 5

  postgres-post:
    image: postgres:15
    container_name: brisq-postgres-post
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${POST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${POST_POSTGRES_DB}
    volumes:
      - postgres_post_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POST_POSTGRES_USER} -d ${POST_POSTGRES_DB}"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: brisq-rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: brisq-auth
    env_file:
      - path: ./auth/.env.development
        required: true
    environment:
      - DATABASE_URL=postgresql://${AUTH_POSTGRES_USER}:${AUTH_POSTGRES_PASSWORD}@postgres-auth:5432/${AUTH_POSTGRES_DB}
      - NODE_ENV=development
    depends_on:
      postgres-auth:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./auth/src
          target: /app/auth/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./auth/package.json
        - action: rebuild
          path: ./common/src

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: brisq-api-gateway
    ports:
      - "3000:3000"
    env_file:
      - path: ./api-gateway/.env.development
        required: true
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./api-gateway/src
          target: /app/api-gateway/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./api-gateway/package.json
        - action: rebuild
          path: ./common/src

volumes:
  postgres_auth_data:
    name: brisq_postgres_auth_data

  postgres_post_data:
    name: brisq_postgres_post_data

  rabbitmq_data:
    name: brisq_rabbitmq_data